name: Lint
on:
  push:
    branches:
      - main
  pull_request:
  merge_group:

jobs:
  golangci:
    # We need to run the linter on the same image we use for building, since it
    # needs the C libraries installed for the dependencies to typecheck.
    runs-on: ubuntu-latest
    container: cometbft/cometbft-db-testing
    steps:
      - uses: actions/checkout@v4
      - uses: golangci/golangci-lint-action@v6
        with:
          # Required: the version of golangci-lint is required and
          # must be specified without patch version: we always use the
          # latest patch version.
          version: latest
          skip-pkg-cache: true
          skip-cache: true
          skip-build-cache: true
          args: --timeout 30m -v
          github-token: ${{ secrets.github_token }}
